#!/usr/bin/env bash
#Configure HAproxy so that it send traffic to web-01 and web-02
#Distribute requests using a roundrobin algorithm
#Make sure that HAproxy can be managed via an init script
#Make sure that your servers are configured with the right hostnames


sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"

frontent linfitech-frontend
	bind*:80
	mode http
	default_backend linfitech-backend

backend linfitech-backend
	balance roundrobin
	server 77862-web-01 54.84.177.239:80 check
	server 77862-web-02 100.24.237.2:80 check
"

"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
