#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Install and configure HAproxy on my lb-01 server.

sudo apt-get -y update
apt-get -y install haproxy

# edit haproxy config file
server_config=\
"
frontend  linfitech-frontend
        bind *:80
        mode http
        default_backend linfitech-backend
backend linfitech-backend
        balance roundrobin
        server 77862-web-01 54.84.177.239:80 check
        server 77862-web-02 100.24.237.2:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg


echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
